export const FETCH_INITIAL_DATA_REQUEST = 'FETCH_INITIAL_DATA_REQUEST';
export const FETCH_INITIAL_DATA_SUCCESS = 'FETCH_INITIAL_DATA_SUCCESS';
export const FETCH_INITIAL_DATA_FAILURE = 'FETCH_INITIAL_DATA_FAILURE';
export const VIEWS = "VIEWS";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const DISABLE_PRODUCT = 'DISABLE_PRODUCT';
export const ENABLE_PRODUCT = 'ENABLE_PRODUCT';
export const DELETE_PRODUCT = "DELETE_PRODUCT";